export { default as VideoBackground } from '../VideoBackground.jsx';
export { default as Header } from '../Header.jsx';
export { default as User } from '../../pages/User.jsx';
export { default as About } from '../../pages/About.jsx';
export { default as Projects } from '../../pages/Projects.jsx';
export { default as Terminal } from '../../pages/Terminal.jsx';
export { default as Contact } from '../../pages/Contact.jsx';
export { default as Footer } from '../Footer.jsx';
export { default as NotFound } from '../../pages/404.jsx';
